name: CI/CD

on:
    push:
        branches:
            - main
jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v4
            - name: Configure node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: npm install
    CD:
        needs: CI
        runs-on: ubuntu-latest
        steps:
            - name: Deploy on vps
              uses: appleboy/ssh-action@v1.0.0
              with:
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                script: |
                    export NVM.DIR=~/.nvm
                    source ~/.nvm/nvm.sh
                    cd /var/www/locations-server/
                    git pull origin main
                    npm install --production
                    pm2 restart src/index.js